CREATE TABLE IF NOT EXISTS stg_matches (
    season   VARCHAR(7),
    `Date`   VARCHAR(16),
    HomeTeam VARCHAR(64),
    AwayTeam VARCHAR(64),
    FTHG VARCHAR(8), FTAG VARCHAR(8), FTR VARCHAR(8),
    HTHG VARCHAR(8), HTAG VARCHAR(8), HTR VARCHAR(8),
    HS VARCHAR(8), `AS` VARCHAR(8), HST VARCHAR(8), AST VARCHAR(8),
    HF VARCHAR(8), AF VARCHAR(8), HC VARCHAR(8), AC VARCHAR(8),
    HY VARCHAR(8), AY VARCHAR(8), HR VARCHAR(8), AR VARCHAR(8)
);
